name: "F5 AST Logic"
version: "0.1.0-23"
slug: "f5_ast_logic"
description: "Core logic. Requires 'General ClickHouse'. Prometheus on port 19091."
arch:
  - amd64
startup: services
boot: auto
# [關鍵修正] 必須為 false，因為我們使用的映像檔已經內建 init 系統
init: false
map:
  - config:rw

ports:
  514/udp: 1514      # Syslog (F5 HSL Target)
  9090/tcp: 19091    # Prometheus Metrics (改為 19091 避開衝突)

options:
  db_host: "172.16.132.2"   # NUC IP
  db_port: 9000           # ClickHouse TCP Port
  db_user: "default"
  db_password: "default"
  analyzer_interval: 300
schema:
  db_host: str
  db_port: int
  db_user: str
  db_password: str
  analyzer_interval: int
